# Generated by Django 4.2 on 2023-04-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recategory",
                        to="category.category",
                    ),
                ),
            ],
            options={"db_table": "category", "managed": True,},
        ),
        migrations.CreateModel(
            name="SearchDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("place_url", models.CharField(max_length=255, null=True)),
                ("x", models.DecimalField(decimal_places=38, max_digits=50)),
                ("y", models.DecimalField(decimal_places=38, max_digits=50)),
                ("category_group_code", models.CharField(max_length=255, null=True)),
                ("category_name", models.CharField(max_length=255, null=True)),
                ("place_name", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
            ],
            options={"db_table": "search_document", "managed": True,},
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("place_url", models.CharField(max_length=255, null=True)),
                ("x", models.DecimalField(decimal_places=38, max_digits=50)),
                ("y", models.DecimalField(decimal_places=38, max_digits=50)),
                ("place_name", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("star_rate", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
            options={"db_table": "place", "managed": True,},
        ),
    ]
